language:
  - python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]];
    then pip install pytest-cov python-coveralls;
    else pip install pytest;
    fi
  - pip install pep8

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/src

script:
  - pep8 --ignore=E501 runtest
  - pep8 --ignore=E501 test/test.py
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]];
    then py.test --cov runtest/* test/test.py;
    else py.test runtest/*;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]];
    then coveralls;
    fi

notifications:
  email: false
