language: python
python:
  - 2.7
install:
  - pip install pytest-cov
  - pip install python-coveralls
  - pip install pep8
script:
  - pep8 --ignore=E501 src/runtest.py
  - py.test --cov src src/runtest.py
after_success:
  - coveralls
