language:
  - python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements.txt

script:
  - pep8 --ignore=E501 runtest
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]];
    then py.test -vv --cov runtest runtest/*.py runtest/test/*.py;
    else py.test -vv               runtest/*.py runtest/test/*.py;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]];
    then coveralls;
    fi

notifications:
  email: false
