language:
  - python

python:
  - 2.7
  - 3.6

install:
  - pip install -r requirements.txt

script:
  - pycodestyle --ignore=E501,E741 runtest
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then py.test -vv --cov runtest runtest/*.py;
    else py.test -vv               runtest/*.py;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]];
    then coveralls;
    fi

notifications:
  email: false
