
# prepare environment
environment:
    matrix:
    - python: C:\Python27;C:\Python27\Scripts
    - python: C:\Python27-x64;C:\Python27-x64\Scripts
    - python: C:\Python34;C:\Python34\Scripts
    - python: C:\Python34-x64;C:\Python34-x64\Scripts

build_script:
# add location of used Python to path
- set path=%path%;%python%
- set PYTHONPATH=%PYTHONPATH%;%CD%\src
# download and upgrade pip
- ps: wget https://bootstrap.pypa.io/get-pip.py -OutFile get-pip.py
- python get-pip.py
# install py.test
- pip install pytest pep8

test_script:
# show environment
- echo %path%
- py.test --version
# run tests
- pep8 --ignore=E501 runtest/runtest.py
- pep8 --ignore=E501 test/test.py
- py.test -vv test/test.py
