environment:
    matrix:
    - python: C:\Python27;C:\Python27\Scripts
    - python: C:\Python27-x64;C:\Python27-x64\Scripts
    - python: C:\Python34;C:\Python34\Scripts
    - python: C:\Python34-x64;C:\Python34-x64\Scripts

build_script:
- set path=%path%;%python%
- set PYTHONPATH=%PYTHONPATH%;%CD%\src
- ps: wget https://bootstrap.pypa.io/get-pip.py -OutFile get-pip.py
- python get-pip.py
- pip install pytest

test_script:
- py.test -vv runtest/check.py
- py.test -vv runtest/extract.py
- py.test -vv runtest/scissors.py
- py.test -vv runtest/tuple_comparison.py
